---
# tasks file for ansible-role-immich-podman

- name: "Include secrets"
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/inventory/{{ secrets_file }}"
    name: "bws"
  when: use_bws

- name: "Set fact"
  ansible.builtin.set_fact:
    secrets: '{{ lookup("community.general.bitwarden_secrets_manager", bws.bws_immich_id, bws_access_token=bws.bws_token).value | from_json }}'
  when: use_bws

- name: "Overwrite vars"
  ansible.builtin.set_fact:
    postgres_password: "{{ secrets.postgres_password }}"
  when: use_bws

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: "directory"
  loop:
    - "{{ base_dir }}/immich"
    - "{{ base_dir }}/immich/model_cache"
    - "{{ base_dir }}/immich/pg_data"

- name: "Copy immich env"
  template:
    force: yes
    src: "immich.env.j2"
    dest: "{{ base_dir }}/immich/immich.env"

- name: "Create immich pod"
  containers.podman.podman_pod:
    name: "{{ pod_name }}"
    state: "created"
    infra_name: "{{ container_prefix }}-infra"
    recreate: no
    ports:
      - "2284:3001" # server

- name: "Immich redis"
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ container_prefix }}-redis"
    image: "docker.io/library/redis:6.2.12-alpine3.18"
    recreate: no
    restart_policy: "no"
    tty: no
    detach: yes
    state: "started"

- name: "Immich postgres"
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ container_prefix }}-postgres"
    image: "docker.io/tensorchord/pgvecto-rs:pg15-v0.2.0"
    recreate: no
    restart_policy: "no"
    tty: no
    detach: yes
    state: "started"
    env_file: "{{ base_dir}}/immich/immich.env"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "{{ base_dir}}/immich/pg_data:/var/lib/postgresql/data:rw,Z"

- name: "Immich server"
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ container_prefix }}-server"
    image: "ghcr.io/immich-app/immich-server:{{ version_tag }}"
    recreate: no
    restart_policy: "no"
    rm: no
    tty: no
    detach: yes
    state: "started"
    volumes: "{{ library_volumes + volumes }}"
    env_file: "{{ base_dir }}/immich/immich.env"
    env:
      NODE_ENV: "production"
  vars:
    volumes:
      - "{{ data_base_dir}}:/usr/src/app/upload:rw,z"
      - "{{ data_encoded_videos_dir }}:/usr/src/app/upload/encoded-video:rw,z"
      - "{{ data_profile_dir }}:/usr/src/app/upload/profile:rw,z"
      - "{{ data_thumbs_dir }}:/usr/src/app/upload/thumbs:rw,z"
      - "{{ data_library_dir }}:/usr/src/app/upload/library:rw,z"

- name: "Immich machine learning"
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ container_prefix }}-machine-learning"
    image: "ghcr.io/immich-app/immich-machine-learning:{{ version_tag }}"
    recreate: no
    restart_policy: "no"
    tty: no
    detach: yes
    state: "started"
    env_file: "{{ base_dir }}/immich/immich.env"
    env:
      NODE_ENV: "production"
    volumes:
      - "{{ base_dir }}/immich/model_cache:/cache:Z"
